project:
  type: website
  output-dir: docs

website:
  title: "Arpita Saggar"
  navbar:
    right:
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: Short CV

format:
  html:
    theme: [lux, assets/research.scss]
    css: assets/styles.css
    toc: true
    smooth-scroll: true