project:
  type: website
  output-dir: docs

website:
  title: "Arpita Saggar"
  navbar:
    right:
      - href: publications.qmd
        text: Publications
      - href: projects.qmd
        text: Projects
      - href: cv.qmd
        text: CV

format:
  html:
    theme: lux
    css: styles.css
    toc: true