project:
  type: website
  output-dir: docs

website:
  search: false 
  twitter-card:
    title: Arpita Saggar
    description: PhD student at the UKRI AI-Medical CDT, University of Leeds
    image: assets/arpita.jpg
  open-graph:
    title: "Arpita Saggar"
    description: "PhD student at the UKRI AI-Medical CDT, University of Leeds"
    image: assets/arpita.jpg
  navbar:
    right:
      - href: index.qmd#sec-news
        text: News
      - href: index.qmd#sec-research
        text: Research
      - href: index.qmd#sec-other
        text: Other Activities
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: [lux, assets/research.scss]
    css: assets/styles.css
    toc: true
    smooth-scroll: true