project:
  type: website
  output-dir: docs

website:
  title: "Arpita Saggar"
  navbar:
    right:
      - href: research.qmd
        text: Research
      - href: activities.qmd
        text: Activities
      - href: cv.qmd
        text: CV

format:
  html:
    theme: lux
    css: styles.css
    toc: true