project:
  type: website
  output-dir: docs

website:
  title: "Arpita Saggar"
  navbar:
    right:
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: Short CV

format:
  html:
    theme: lux
    css: assets/styles.css
    toc: true