project:
  type: website
  output-dir: docs

website:
  navbar:
    right:
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: Short CV
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: [lux, assets/research.scss]
    css: assets/styles.css
    toc: true
    smooth-scroll: true